# This workflow will install Python dependencies and run tests with PyTest using Python 3.11
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Set Python version
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Set up submodules and submodule dependencies
      - name: Set up submodule and submodule dependencies
        run: |
          git submodule update --init --recursive --remote
          git submodule foreach "pip install -r requirements.txt"

      # Install project dependencies
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-pytorch.txt

      # Run linters and formatters
      - name: Linters and formatters
        run: |
          black --check .
          flake8 .
          pylint .

      # Run unit tests with PyTest
      - name: Run unit tests
        run: pytest -vv
